RoadRecordViolationSystem/Controllers/LogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RoadRecordViolationSystem.Models;
using RoadRecordViolationSystem.Services;
using RoadRecordViolationSystem.Services.Interfaces;
using RoadRecordViolationSystem.ViewModels;
using System;
using System.Threading.Tasks;

namespace RoadRecordViolationSystem.Controllers
{
    public class LogController : Controller
    {
        #region private fields
        private readonly ILogProvider<LoginViewModel> _login;
        private readonly IAuthorizedProvider<ApplicationUser> _auth;
        private readonly UserManager<ApplicationUser> _user;
        private readonly IlogHistory _historyService;
        private readonly SignInManager<ApplicationUser> _signIn;
        private readonly ICrudRepository<UsersInformation> _userService;
        #endregion

        #region constructor dependency injection
        public LogController(ILogProvider<LoginViewModel> login, IAuthorizedProvider<ApplicationUser> auth, UserManager<ApplicationUser> user,IlogHistory historyService,SignInManager<ApplicationUser> signIn
            , ICrudRepository<UsersInformation> userService)
        {
            _login = login;
            _auth = auth;
            _user = user;
            _historyService = historyService;
            _signIn = signIn;
            _userService = userService;

        }
        #endregion

        #region controller actions

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> SystemLogin()
        {
  
            if (_signIn.IsSignedIn(User))
            {
                var account = await _user.FindByNameAsync(User.Identity.Name);
                ViewBag.AuthLayout = await _auth.GetAuthLayoutAsync(account, "Enforcer");

                var userInfo =await _userService.GetByIdAsync(account.UsersInfoId);

                HttpContext.Session.SetString("UserFullName", $"{userInfo.GivenName} {userInfo.MiddleName}. {userInfo.LastName}");
                HttpContext.Session.SetString("ProfilePicture", account.ProfilePicture);

                return View(_auth.GetAuthView());
            }
            else
            {

                return View();

            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> SystemLogin(LoginViewModel credentials)
        {
            ViewBag.DisableLogin = null;

            if (ModelState.IsValid)
            {
                var account = await _user.FindByNameAsync(credentials.UserName);

                if (account != null && account.ValidTimeToLogin != null && DateTime.Now.TimeOfDay >= account.ValidTimeToLogin.Value.TimeOfDay)
                {
                    account.AccessFailedCount = 0;
                    account.ValidTimeToLogin = null;
                    await _user.UpdateAsync(account);
                    ViewBag.DisableLogin = false;
                }
                else if (account != null && account.AccessFailedCount == 5)
                {
                    ViewBag.ErrorLogin = "You have attempted 5 invalid logins please wait for 5 minutes Thank you!";
                    ViewBag.DisableLogin = true;
                    account.ValidTimeToLogin =  DateTime.Now.AddMinutes(5);
                    await _user.UpdateAsync(account);

                    return View();
                }
                 if (account != null && account.AccountStatus == "ARCHIVE")
                {
                    ViewBag.ErrorLogin = "Your Account is Deactivated please contact Primary Administrator Thank you !";
                    return View();
                }

                else if (await _login.IsAuthenticateAsync(credentials) && account.AccountStatus == "ACTIVE")
                {
                    ViewBag.AuthLayout = await _auth.GetAuthLayoutAsync(account, "Enforcer");

                    DateTime dateNow = DateTime.Now;
                    
                    await _historyService.RecordlogInAsync(account.Id,dateNow.ToLongDateString(),dateNow.ToLongTimeString());

                    HttpContext.Session.SetString("DateIn", dateNow.ToLongDateString());
                    HttpContext.Session.SetString("TimeIn", dateNow.ToLongTimeString());
                    HttpContext.Session.SetString("UserLogId", account.Id);

                    return RedirectToAction(nameof(ShowAauthView), new { viewPath = _auth.GetAuthView(),userId = account.UsersInfoId,profilePicture = account.ProfilePicture });
                }
                else if (!await _login.IsAuthenticateAsync(credentials))
                {
                    ViewBag.ErrorLogin = "Invalid Username or password";

                    if (account != null)
                    {
                        account.AccessFailedCount += 1;
                        await _user.UpdateAsync(account);
                    }

                    return View();
                }
            }
            return View(credentials);
        }
        [AllowAnonymous]
        public async Task<IActionResult> ShowAauthView(string viewPath,int userId, string profilePicture)
        {
            var userInfo = await _userService.GetByIdAsync(userId);

            HttpContext.Session.SetString("UserFullName", $"{userInfo.GivenName} {userInfo.MiddleName}. {userInfo.LastName}");
            HttpContext.Session.SetString("ProfilePicture", profilePicture);

            return View(viewPath);
        }

        [Authorize]
        public async Task<IActionResult> Logout(ApplicationUser user)
        {
            await _login.Logout();
            await _historyService.RecordLogOutAsync();

            HttpContext.Session.Clear();
            return RedirectToAction(nameof(SystemLogin));

            
        }
        #endregion
    }
}

RoadRecordViolationSystem/Views/Shared/_CssStylePartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.1.0/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="~/css/site.css" />
<link rel="icon" href="~/homePageImage/dpos-logo.png" />
<link href="https://fonts.cdnfonts.com/css/roboto" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

RoadRecordViolationSystem/Views/Shared/_EnforcerLayout.cshtml
@using RoadRecordViolationSystem.ViewModels;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <partial name="_MetaTagsPartial" />
    <partial name="_CssStylePartial" />
    <link rel="stylesheet" href="~/css/loaders/spinkit.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script type="text/javascript">
        function preventBack() {
            window.history.forward();
        }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>
</head>

<body>
    <style>
        body {
            font-family: Montserrat,'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }
    </style>
    <div class="top-header" style="background-color:white;">
        <img src="@Url.Content(HttpContextAccessor.HttpContext.Session.GetString("ProfilePicture"))" id="profile-picture" class="img-fluid rouded-circle mx-3">
        <div class="dropdown float-end">
            <button class="  text-dark bg-white fw-bold text-center" style=" font-size:9px; border:none; margin-top:13px;" data-bs-toggle="dropdown">@HttpContextAccessor.HttpContext.Session.GetString("UserFullName")<br/>ENFORCER</button>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="MyAccount" asp-action="MyAccountView"><i class="bi bi-person-circle fa "></i>My Profile</a>
                <a class="dropdown-item" style="cursor:pointer" onclick="showMyLogHistoryModal('/CurrentUserLogHistory/ModalView','My Log History',null)"><i class="bi bi-gear"></i>My Log History</a>
                <a class="dropdown-item" asp-controller="Log" asp-action="LogOut"><i class="bi bi-box-arrow-right"></i>Log Out</a>
            </div>
        </div>
        <a style="font-size:15px; margin-top:12px; text-decoration-line:none;" class="fw-bold text-dark float-start  mx-2" asp-controller="Dashboard" asp-action="ScanQR">DPOS</a>
    </div>


    <div id="main-container" class="container-fluid text-nowrap mt-5 pt-3">
        @RenderBody()
    </div>

    <div id="my-loghistory-modal-holder"></div>
    <partial name="_JavaScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
    <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script>
    <script src="~/js/Scoped/Dashboard/qrscan.js"></script>
    <script src="~/js/Global/someAddRemover.js"></script>
    <script src="~/js/Scoped/MyLogHistory/myloghistory.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</body>
</html>

RoadRecordViolationSystem/Views/Shared/_JavaScriptsPartial.cshtml
<script src="~/lib/jquery/jquery.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.print.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.colVis.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/limonte-sweetalert2/sweetalert2.all.min.js"></script>
<script src="~/lib/Chart.js/chart.min.js"></script>
<script type="text/javascript" src="~/js/Global/navigationBar.js"></script>

RoadRecordViolationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="icon" href="~/homePageImage/dpos-logo.png" />
    </head>
    <body>
        <div class="top-header">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle float-end mt-2 mx-2" data-bs-toggle="dropdown">System User</button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#"><i class="bi bi-person-circle fa "></i>My Profile</a>
                    <a class="dropdown-item" href="#"><i class="bi bi-gear"></i>Account Settings</a>
                    <a class="dropdown-item" href="#"><i class="bi bi-box-arrow-right"></i>Log Out</a>
                </div>
            </div>
            <img src="profile.png">
        </div>

        <div class="temp-sidebar">
        </div>

        <nav class="sidebar">
            <i class="btn-hide fas fa-list fa"></i>
            <h4 class="sidebar-header">SYSTEM</h4>
            <ul class="sidebar-menu">
            </ul>
        </nav>
        <div class="container-fluid mt-5 pt-3 text-nowrap">
            @RenderBody()
        </div>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

RoadRecordViolationSystem/Views/Shared/_MetaTagsPartial.cshtml
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

RoadRecordViolationSystem/Views/Shared/_NonEnforcerLayout.cshtml
@using RoadRecordViolationSystem.ViewModels;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor



<!DOCTYPE html>
<html>
<head>
    <partial name="_MetaTagsPartial" />
    <partial name="_CssStylePartial" />
</head>
<body>
    <div class="top-header">
        <img src="@Url.Content(HttpContextAccessor.HttpContext.Session.GetString("ProfilePicture"))" class="img-fluid rouded-circle mx-3">
        <div class="dropdown">
            <button class=" float-end text-white fw-bold" style="background-color:#03506F; border:none; font-size:9px; margin-top:11px;" data-bs-toggle="dropdown">@HttpContextAccessor.HttpContext.Session.GetString("UserFullName")<br/>ADMINISTRATOR</button>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="MyAccount" asp-action="MyAccountView"><i class="bi bi-person-circle fa "></i>My Profile</a>
                <a class="dropdown-item" style="cursor:pointer" onclick="showMyLogHistoryModal('/CurrentUserLogHistory/ModalView','My Log History',null)"><i class="bi bi-gear"></i>My Log History</a>
                <a class="dropdown-item" asp-controller="Log" asp-action="LogOut"><i class="bi bi-box-arrow-right"></i>Log Out</a>
            </div>
        </div>
    </div>

    <div class="temp-sidebar">
        <p style="color: #DFE2EA;">Space</p>
    </div>

    <nav class="sidebar">
        <i class="btn-hide bi bi-list"></i>
        <p class="sidebar-header h6">DPOS Violation System</p>
        <ul class="sidebar-menu">
            <li><a asp-action="GetDashboardView" asp-controller="Dashboard"><i class="bi bi-clipboard-data"></i>Dashboard</a> </li>
            <li><a asp-action="AccountList" asp-controller="AdminAccounts"><i class="bi bi-people"></i>Account List</a> </li>
            <li><a asp-action="LogHistoryList" asp-controller="UsersLogHistory"><i class="bi bi-card-list"></i>Log History</a> </li>
            <li><a asp-action="Index" asp-controller="ViolationTypes"><i class="bi bi-exclamation-circle"></i>Violation Types</a> </li>
            <li><a asp-action="Index" asp-controller="Violator"><i class="bi bi-person-bounding-box"></i>Violators</a> </li>
            <li><a asp-action="Index" asp-controller="Transaction"><i class="bi bi-wallet2"></i>Violations</a> </li>
            <li><a asp-action="Index" asp-controller="Accident"><i class="bi bi-cone-striped"></i>Accidents</a> </li>
            <li><a asp-action="Index" asp-controller="Contest"><i class="bi bi-card-heading"></i>Contest</a> </li>
            <li><a asp-action="Index" asp-controller="Archive"><i class="bi-file-zip-fill"></i>Archives</a> </li>
            <li><a asp-action="Index" asp-controller="Setting"><i class="bi bi-gear"></i>Settings</a> </li>
        </ul>
    </nav>

    <div id="main-container" class="container-fluid text-nowrap mt-5 pt-3">
        @RenderBody()
    </div>

    <div id="my-loghistory-modal-holder"></div>

    <!--required global scripts-->
    <partial name="_JavaScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
    <!--end required global scripts-->
    <!--Dropdown scripts-->
    <script src="~/js/Scoped/MyLogHistory/myloghistory.js"></script>
    <!--end Dropdown scripts-->
    <script src="~/js/Global/someAddRemover.js"></script>
</body>
</html>